### ISSUE TITLE
why clamp the notes

### ISSUE THREAD

**Issue by HyperBeast43** [Grinjr/WEBFISHING-Midi-Input#2]
just transpose them down by an octave or two until they fit in the range??

**Comment by Grinjr** [comment]
I was actually going to look into doing this, but at this point I think it would be better to recommend using [Midi Strummer](https://github.com/puppy-girl/MidiStrummer) instead, and recommending this to them, or at least recommending this as an option in the mod's config.
I had plans to convert this tool into a mod to add more native midi input, but they beat me to the punch and no point in reinventing the wheel. If it's something I really wish for enough, I might consider making a fork of their mod and adding it. But for now, their tool would probably be better to use and to suggest this to!
